--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.1.22.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2023. 03. 09. 21:18:33
-- Server version: 5.5.5-10.4.25-MariaDB
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

DROP DATABASE IF EXISTS database1;

CREATE DATABASE IF NOT EXISTS database1
	CHARACTER SET utf8
	COLLATE utf8_hungarian_ci;

--
-- Set default database
--
USE database1;

--
-- Create table `regions`
--
CREATE TABLE IF NOT EXISTS regions (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 5,
AVG_ROW_LENGTH = 4096,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create table `characters`
--
CREATE TABLE IF NOT EXISTS characters (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  regionId INT(11) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 65,
AVG_ROW_LENGTH = 256,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create foreign key
--
ALTER TABLE characters 
  ADD CONSTRAINT FK_characters_regions_id FOREIGN KEY (regionId)
    REFERENCES regions(id);

-- 
-- Dumping data for table regions
--
INSERT INTO regions VALUES
(1, 'Mondstadt'),
(2, 'Liyue'),
(3, 'Inazuma'),
(4, 'Sumeru');

-- 
-- Dumping data for table characters
--
INSERT INTO characters VALUES
(1, 'Jean', 1),
(2, 'Amber', 1),
(3, 'Lisa', 1),
(4, 'Kaeya', 1),
(5, 'Barbara', 1),
(6, 'Diluc', 1),
(7, 'Razor', 1),
(8, 'Venti', 1),
(9, 'Klee', 1),
(10, 'Bennett', 1),
(11, 'Noelle', 1),
(12, 'Fischl', 1),
(13, 'Sucrose', 1),
(14, 'Mona', 1),
(15, 'Diona', 1),
(16, 'Albedo', 1),
(17, 'Rosaria', 1),
(18, 'Eula', 1),
(19, 'Aloy', 1),
(20, 'Mika', 1),
(21, 'Xiao', 2),
(22, 'Beidou', 2),
(23, 'Ningguang', 2),
(24, 'Xiangling', 2),
(25, 'Xinqiu', 2),
(26, 'Chongyun', 2),
(27, 'Qiqi', 2),
(28, 'Keqing', 2),
(29, 'Tartaglia', 2),
(30, 'Zhonli', 2),
(31, 'Xinyan', 2),
(32, 'Ganyu', 2),
(33, 'Hu Tao', 2),
(34, 'Yanfei', 2),
(35, 'Shenhe', 2),
(36, 'Yun Jin', 2),
(37, 'Yelan', 2),
(38, 'YaoYao', 2),
(39, 'Ayaka', 3),
(40, 'Kazuha', 3),
(41, 'Yoimiya', 3),
(42, 'Sayu', 3),
(43, 'Raiden', 3),
(44, 'Sara', 3),
(45, 'Kokomi', 3),
(46, 'Thoma', 3),
(47, 'Itto', 3),
(48, 'Gorou', 3),
(49, 'Yae Miko', 3),
(50, 'Ayato', 3),
(51, 'Shinobu', 3),
(52, 'Heizou', 3),
(53, 'Tighnari', 4),
(54, 'Collei', 4),
(55, 'Dori', 4),
(56, 'Cyno', 4),
(57, 'Candace', 4),
(58, 'Nilou', 4),
(59, 'Nahida', 4),
(60, 'Layla', 4),
(61, 'Wanderer', 4),
(62, 'Faruzan', 4),
(63, 'Alhaitam', 4),
(64, 'Dehya', 4);

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;